### ISSUE TITLE
dataset URL is broken

### ISSUE THREAD

**Issue by miguelfs** [DaphneO/DECIBEL#4]
```
Download data folder from https://drive.google.com/drive/u/1/folders/[1WhMnm76ZXkEOARdzoFoHeBfykHRdqkJ_](https://daphneo.github.io/DECIBEL/html/installation.html#id1) and store it on your computer. This folder will be filled with (intermediate) results, tables, figures, etc. The total size of this folder will be around 12 GB, so make sure that you have enough space. It is possible to store the data on an external hard drive.
```

<img width="823" alt="image" src="https://github.com/DaphneO/DECIBEL/assets/10662585/d9b71a79-4175-4345-b253-acd694d7fe3c">

**Comment by DaphneOdekerken** [comment]
Hi Miguel,
Thanks for the message, it seems that the link is broken. I'll try to fix this on the documentation page ASAP, but for now you can use the link https://drive.google.com/drive/u/0/folders/1WhMnm76ZXkEOARdzoFoHeBfykHRdqkJ_ 
That should work.
